#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xbattbar -c -t 1 &
fcitx5 -d &
urxvtd -q -o &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config focused_border_color "#808080"
bspc config window_gap          0
bspc config bottom_padding	1

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a xbattbar layer=above

urxvtc &
